# Generated by Django 4.1.7 on 2023-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
