# Generated by Django 4.1.7 on 2023-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_userprofile_date_created_userprofile_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pictures"),
        ),
    ]
