# Generated by Django 4.1.7 on 2023-04-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_email",
        ),
    ]
