# Generated by Django 4.1.7 on 2023-04-25 11:00

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_remove_userprofile_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(upload_to=Users.models.csv_upload_to),
        ),
    ]
