# Generated by Django 4.1.7 on 2023-04-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csv",
            old_name="user",
            new_name="csv",
        ),
    ]
