# Generated by Django 4.1.7 on 2023-04-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0006_remove_csv_csv_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csv",
            name="user",
        ),
    ]
