# Generated by Django 4.1.7 on 2023-04-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploads", "0008_csv_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csv",
            name="date_uploaded",
        ),
        migrations.RemoveField(
            model_name="csv",
            name="file",
        ),
        migrations.AddField(
            model_name="csv",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
