# Generated by Django 4.1.7 on 2023-04-24 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploads", "0010_csv_date_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csv",
            name="date_uploaded",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="csv",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
