# Generated by Django 4.1.7 on 2023-04-24 14:49

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0011_alter_csv_date_uploaded_alter_csv_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csv",
            name="csv_file",
            field=models.FileField(upload_to=uploads.models.csv_upload_to),
        ),
    ]
